#!/usr/bin/env bash

./commit-msg "examples/00-ok" >/dev/null

if [ $? -ne 0 ]
then
	echo "FAIL: \`./commit-msg examples/00-ok\` should exit with code 0"
	exit 1
fi

for INDEX in 01 02 03 04 05 06
do

	ACTUAL=$(./commit-msg "examples/$INDEX-message" 2>&1)

	if [ $? -ne 1 ]
	then
		echo "FAIL: \`./commit-msg \"examples/$INDEX-message\" 2>&1\` should exit with code 1"
		exit 1
	fi

	EXPECTED=$(cat "examples/$INDEX-validation")

	if ! [ "$ACTUAL" = "$EXPECTED" ]
	then
		echo "FAIL: \`./commit-msg \"examples/$INDEX-message\" 2>&1\` should should output:"
		echo "$EXPECTED"
		exit 1
	fi

done

echo "All Tests Passed"
